cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cart/', show_cart, name='cart'),
    path('add_to_cart/<int:pk>/', add_to_cart, name='add_to_cart'),
]

teams/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main, name='home_page'),
    path('update-team/<slug:slug>/', team_update, name='team_update'),
    path('team/<slug:slug>/', TeamDetailView.as_view(), name='team'),
    path('teams/', Teams.as_view(), name='teams'),
    path('my_teams/', users_fav_teams, name='users_fav_teams'),
]

teams/models.py
from django.db import models
from django.urls import reverse

class Team(models.Model):
    name = models.CharField(max_length=250)
    date_of_foundation = models.DateField(blank=True, null=True)
    logo = models.ImageField(null=True, blank=True, default='default_logo.jpg')
    bio = models.TextField(null=True, blank=True)
    #coach
    country = models.CharField(max_length=70, db_index=True)
    stadium = models.CharField(max_length=200, null=True, blank=True)
    titles = models.TextField(null=True, blank=True)
    players_amount = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(null=True, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Match(models.Model):
    team_home = models.ForeignKey(Team, blank=False, null=False, on_delete=models.CASCADE, related_name='team_home')
    team_away = models.ForeignKey(Team, blank=False, null=False, on_delete=models.CASCADE,  related_name='team_away')
    date = models.DateTimeField()
    tournament = models.CharField(max_length=200, blank=True, null=True)
    referee = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=300, blank=True, null=True)
    finished = models.BooleanField(default=0)

    class Meta:
        verbose_name_plural = 'Matches'

    def __str__(self):
        return f'{self.team_home} - {self.team_away}'

teams/forms.py
from django.forms import ModelForm
from .models import Team


class TeamUpdateForm(ModelForm):
    class Meta:
        model = Team
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(TeamUpdateForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

teams/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from teams.models import Team, Match
from users.models import Profile
from .forms import TeamUpdateForm

from django.contrib import admin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.models import User, Permission
def main(request):
    matches = Match.objects.all()
    context = {'matches': matches}
    return render(request, 'main.html', context)


def users_fav_teams(request):
    try:
        profile = request.user.profile
        teams = profile.favorite_teams.all()
    except:
        profile = None
        teams = None
    context = {'profile': profile, 'teams': teams}
    return render(request, 'teams/users_fav_teams.html', context)


class Teams(ListView):
    model = Team
    template_name = 'teams/teams_all.html'
    paginate_by = 3

    def get_queryset(self):
        name = self.request.GET.get('team_name', None)
        if name:
            teams = self.model.objects.filter(name__icontains=name)
        else:
            teams = self.model.objects.all()
        return teams

    def get_context_data(self, *args, **kwargs):
        context = super(Teams, self).get_context_data(**kwargs)
        context['team_name'] = self.request.GET.get('team_name', None)
        return context


class TeamDetailView(DetailView):
    # permission_required = 'teams.view_team'
    model = Team
    template_name = 'teams/team.html'

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        team = context['team']
        try:
            matches = Match.objects.filter(Q(team_home=team) | Q(team_away=team))
        except:
            matches = None
        context['matches'] = matches


        team_id = context['team'].id
        teams = None

        if 'recently_viewed' in self.request.session:
            if team_id in self.request.session['recently_viewed']:
                self.request.session['recently_viewed'].remove(team_id)

            teams = Team.objects.filter(pk__in=self.request.session['recently_viewed'])

            self.request.session['recently_viewed'].insert(0, team_id)
            if len(self.request.session['recently_viewed']) > 4:
                self.request.session['recently_viewed'].pop()

        else:
            self.request.session['recently_viewed'] = [team_id]


        self.request.session.modified = True

        context['recently_viewed_products'] = teams

        return context



@permission_required("teams.update_team")
def team_update(request, slug):
    team = Team.objects.get(slug=slug)
    form = TeamUpdateForm(instance=team)
    if request.method == 'POST':
            form = TeamUpdateForm(request.POST,  request.FILES, instance=team)
            if form.is_valid():
                form.save()
                return redirect('teams')

    context = {'form': form}
    return render(request, 'teams/team_update.html', context)

templates/teams/team.html
{% extends 'main.html' %}

{% block content %}
<div class="team_main" style="text-align:center">

    <h3>{{team.name}} </h3>
<img src="{{team.logo.url }}" alt="" height="200px">
    <h5>Country:  {{team.country}}</h5>
    <hr>

{% for match in matches %}
   <ul>{{match.team_home.name }} <img src="{{ match.team_home.logo.url }}" alt="" height="30px"> -
        {{match.team_away.name }} <img src="{{ match.team_away.logo.url }}" alt="" height="30px">
   </ul>
{% endfor %}


    <a href="{% url 'team_update' team.slug %}"> Update</a>

</div>

{% for team in recently_viewed_products %}
    {{ team.name }}
<img src="{{ team.logo.url }}" alt="" height="30px">

{% endfor %}

{% endblock %}

templates/teams/team_update.html
{% extends 'main.html' %}

{% block content %}
<form class="form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit"> Update </button>
</form>


{% endblock %}

templates/teams/teams_all.html
{% extends 'main.html' %}

{% block content %}
    <form method="get" action="{% url 'teams' %}"
          class="form-inline my-2 my-lg-0" style="display: flex; justify-content: center;">
      <input class="form-control mr-sm-2" type="search"
             placeholder="Search" aria-label="Search" name="team_name">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
{% for team in team_list %}
<div class="card" style="width: 20rem; display: inline-block;">
 <a href="{{ team.get_absolute_url }}"><img class="card-img-top" src="{{team.logo.url }}"></a>
  <div class="card-body">
    <h5 class="card-title">{{ team.name }}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{{ team.get_absolute_url }}" class="btn btn-primary">Go somewhere</a>

  </div>
</div>

{% endfor %}

<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link"
                             href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}
    <li class="page-item"> <a class="page-link" href="#">
        {{ page_obj.number }} </a>
    </li>

      {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link"
                             href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
  </ul>
</nav>

{% endblock %}

templates/teams/users_fav_teams.html
{% extends 'main.html' %}

{% block content %}

<h1> Teams </h1>

{% if teams %}

{% for team in profile.favorite_teams.all %}
<div class="card" style="width: 30rem; display: inline-block;  margin-left: 30px; height: 60rem;">
 <a href="{{ team.get_absolute_url }}"><img class="card-img-top" src="{{team.logo.url }}"></a>
  <div class="card-body">
    <h5 class="card-title">{{ team.name }}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
      <hr>
      {% for match in team.team_home.all %}
    <h5 class="card-title">
                <img class="card-img-top" src="{{match.team_home.logo.url }}" style="width: 20px; margin-left: 15px;">
        {{ match.team_home.name }} - {{ match.team_away.name }}
            <img class="card-img-top" src="{{match.team_away.logo.url }}" style="width: 20px; margin-right: 10px;">
    </h5>
      {% endfor %}
      {% for match in team.team_away.all %}
    <h5 class="card-title">
                <img class="card-img-top" src="{{match.team_home.logo.url }}" style="width: 20px; margin-left: 15px;">
        {{ match.team_home.name }} - {{ match.team_away.name }}
            <img class="card-img-top" src="{{match.team_away.logo.url }}" style="width: 20px; margin-right: 10px;">
    </h5>
      {% endfor %}
  </div>
</div>

{% endfor %}

{% else %}
<h1> У вас пока нет любимой команды.
    Вы можете добавить ее <a href="{% url 'login' %}">авторизовавшись</a>
</h1>
{% endif %}
{% endblock %}